import React, { createContext, useState, useEffect, useCallback, useMemo, ReactNode } from 'react';

// Arabic Translations (Default)
const arTranslations: Record<string, string> = {
    "appTitle": "إمداد التطور",
    "appSubtitle": "للخدمات اللوجستية",
    "logout": "تسجيل الخروج",
    "strategicGuidance": "التوجيه الاستراتيجي",
    "adminBoard": "لوحة الإدارة",
    "myRequests": "قسم طلباتي",
    "hrDelegateManagement": "إدارة المناديب",
    "allDelegates": "المناديب",
    "resignedDelegates": "المناديب المستقيلون",
    "operationsTools": "أدوات العمليات",
    "reports": "التقارير",
    "complianceShield": "درع الالتزام",
    "suspendedDelegates": "المناديب الموقوفون",
    "readyMessages": "رسائل جاهزة",
    "guidanceAndCirculars": "التوجيه والتعاميم",
    "staffManagement": "إدارة الموظفين",
    "selfPreparation": "التحضير الذاتي",
    "chooseYourRole": "اختر دورك الوظيفي",
    "supervisorAccount": "اختر حساب المشرف",
    "password": "كلمة المرور",
    "login": "ولوج",
    "delegateSection": "قسم المناديب",
    "openDelegateApp": "فتح تطبيق المندوب",
    "backToMainDashboard": "العودة إلى لوحة التحكم الرئيسية",
    "error_incorrectPassword": "كلمة المرور غير صحيحة.",
    "error_selectSupervisor": "الرجاء اختيار مشرف.",
    "error_invalidRole": "الدور الوظيفي غير صالح.",
    "error_selectRole": "الرجاء اختيار دورك الوظيفي.",
    "strategicGuidanceBoard": "لوحة التوجيه الاستراتيجي",
    "primaryGoal": "الهدف الأساسي",
    "primaryGoalAdvice": "تحقيق متوسط 15 طلبًا يوميًا لكل مندوب لضمان أعلى مستويات الإنتاجية والربحية.",
    "tipOfTheDay": "نصيحة اليوم",
    "tipOfTheDayAdvice": "ركز على تحفيز المناديب ذوي الأداء المتوسط، فهم يمثلون أكبر فرصة للنمو السريع.",
    "successIndicator": "مؤشر للنجاح",
    "successIndicatorAdvice": "التواصل اليومي الفعال مع الفريق لمدة 5 دقائق يرفع الروح المعنوية ويعزز الأداء بشكل ملحوظ.",
    "aiPerformanceAnalysis": "تحليل الأداء الذكي بواسطة Gemini",
    "analyzePerformance": "تحليل شامل للأداء",
    "readyForInsights": "جاهز للحصول على رؤى عميقة؟",
    "clickAnalyzeButton": "اضغط على زر التحليل لبدء تقييم أداء فريقك بواسطة الذكاء الاصطناعي.",
    "supervisorAccountability": "مساءلة المشرفين",
    "delegatePerformanceBoard": "لوحة أداء المناديب",
    "export": "تصدير",
    "table_supervisor": "المشرف",
    "table_totalDelegates": "إجمالي المناديب",
    "table_active": "النشطون",
    "table_suspended": "الموقوفون",
    "table_performanceIndex": "مؤشر الأداء",
    "table_delegate": "المندوب",
    "table_delegateId": "المعرف",
    "table_currentStatus": "الحالة الحالية",
    "table_notes": "ملاحظات",
    "table_suggestedAction": "الإجراء المقترح",
    "unknown": "غير معروف",
    "action_followUp": "متابعة",
    "action_monitor": "مراقبة",
    "action_suspend": "إيقاف",
    "action_terminate": "إنهاء خدمة",
    "confirm": "تأكيد",
    "areYouSureYouWantTo": "هل أنت متأكد من أنك تريد",
    "theDelegate": "المندوب",
    "yes": "نعم",
    "cancel": "إلغاء",
    "supervisorInCharge": "المشرف المسؤول",
    "suspensionNotes": "ملاحظات الإيقاف",
    "noNotesRecorded": "لا توجد ملاحظات مسجلة.",
    "noSuspendedDelegates": "لا يوجد مناديب موقوفون حاليًا.",
    "smartMessageGenerator": "مولد الرسائل الذكي",
    "chooseReadyTopic": "اختر موضوعًا جاهزًا",
    "enterCustomTopic": "أو أدخل موضوعًا مخصصًا",
    "create": "إنشاء",
    "customTopicPlaceholder": "مثال: رسالة تحفيزية لبداية الأسبوع",
    "generatedMessage": "الرسالة المنشأة",
    "copyToClipboard": "نسخ إلى الحافظة",
    "copySuccess": "تم النسخ بنجاح!",
    "copyFail": "فشل النسخ.",
    "reminderStartWork": "تذكير ببدء وقت العمل",
    "warningRepeatedDelay": "تحذير بشأن التأخير المتكرر",
    "thanksExcellentPerformance": "شكر وتقدير على الأداء الممتاز",
    "noticePolicyUpdate": "إشعار بوجود تحديث في سياسة الشركة",
    "queryAbsenceFromWorkArea": "استفسار عن سبب عدم التواجد في منطقة العمل",
    "comprehensiveReports": "التقارير الشاملة",
    "delegatePerformanceReport": "تقرير أداء المناديب",
    "timePeriod": "الفترة الزمنية",
    "daily": "يومي",
    "weekly": "اسبوعي",
    "monthly": "شهري",
    "custom": "مخصص",
    "to": "إلى",
    "delegateType": "نوع المندوب",
    "kafalaDelegates": "مناديب الكفالة",
    "ajirDelegates": "مناديب أجير",
    "totalKafalaOrders": "إجمالي طلبات مناديب الكفالة (الفترة المحددة)",
    "totalAjirOrders": "إجمالي طلبات مناديب أجير (الفترة المحددة)",
    "delegateName": "اسم المندوب",
    "delegateID": "المعرف",
    "nationalId": "رقم الهوية",
    "phoneNumber": "رقم الجوال",
    "joinDate": "تاريخ الانضمام",
    "resignationDate": "تاريخ الاستقالة",
    "orderCount": "عدد الطلبات",
    "noDataMatchingFilters": "لا توجد بيانات تطابق الفلاتر المحددة.",
    "dailyPreparationSection": "قسم التحضير اليومي",
    "weekendAbsence": "غياب الويكند (خ/ج/س)",
    "thursday_short": "خ",
    "friday_short": "ج",
    "saturday_short": "س",
    "internalRequests": "طلبات داخلية",
    "employeeRequests": "طلبات الموظفين",
    "createNewRequest": "إنشاء طلب جديد",
    "createNewInternalRequest": "إنشاء طلب داخلي",
    "status_pending": "معلق",
    "status_inProgress": "قيد الإجراء",
    "status_completed": "مكتمل",
    "from": "من",
    "requestDescription": "وصف الطلب",
    "writeYourComment": "اكتب تعليقك هنا...",
    "requestType": "نوع الطلب",
    "requestType_internal": "طلبات داخلية (بين الإدارات)",
    "requestType_employee": "طلبات الموظفين (إلى مندوب)",
    "requestTitle": "عنوان الطلب",
    "selectDepartment": "اختر الإدارة",
    "selectDelegate": "اختر المندوب",
    "requestCreated": "تم إنشاء الطلب.",
    "error_fillAllFields": "الرجاء تعبئة جميع الحقول",
    "delegateApp": "تطبيق المندوب",
    "enterYourPhoneNumber": "أدخل رقم جوالك",
    "next": "التالي",
    "welcomeBackEnterPassword": "أهلاً بك! الرجاء إدخال كلمة المرور للمتابعة.",
    "changeNumber": "تغيير الرقم",
    "error_phoneNotFound": "رقم الجوال غير مسجل في النظام.",
    "error_endShiftToLogout": "يرجى إنهاء الدوام قبل تسجيل الخروج",
    "deliveryDelegate": "مندوب توصيل",
    "currentAssignment": "المهمة الحالية",
    "noAssignment": "لا توجد مهمة مسندة حالياً.",
    "startShiftToReceive": "يجب بدء الدوام لاستقبال المهام.",
    "youAreOnDuty": "أنت الآن في الخدمة",
    "shiftIsOff": "الدوام متوقف",
    "performanceEvaluation": "تقييم الأداء",
    "todaysOrders": "طلبات اليوم",
    "gps_inactive": "GPS غير نشط",
    "gps_active": "GPS نشط",
    "gps_error": "خطأ في GPS",
    "startShift": "بدء الدوام",
    "endShift": "إنهاء الدوام",
    "dashboard": "الرئيسية",
    "writeYourReply": "اكتب ردك هنا...",
    "role_GeneralManager": "المدير العام",
    "role_MovementManager": "مدير الحركه والتشغيل",
    "role_OpsSupervisor": "الإدارة التشغيلية",
    "role_HR": "اداره الموارد البشريه",
    "role_Finance": "الادارة المالية",
    "role_Legal": "الشوؤن القانونية",
    "perfStatus_ممتاز": "ممتاز",
    "perfStatus_متوسط": "متوسط",
    "perfStatus_ضعيف": "ضعيف",
    "perfStatus_موقوف": "موقوف",
    "addDelegate": "إضافة مندوب",
    "editDelegate": "تعديل مندوب",
    "iqamaPhoto": "صورة الإقامة",
    "licensePhoto": "صورة الرخصة",
    "personalPhoto": "الصورة الشخصية",
    "uploadFile": "رفع ملف",
    "preview": "معاينة",
    "assignSupervisor": "تعيين المشرف",
    "delegateStatus": "حالة المندوب",
    "active": "نشط",
    "resigned": "مستقيل",
    "save": "حفظ",
    "error_id_6_digits": "يجب أن يتكون المعرف من 6 أرقام.",
    "error_phone_10_digits": "يجب أن يتكون رقم الجوال من 10 أرقام.",
    "error_nationalId_10_digits": "يجب أن يتكون رقم الهوية من 10 أرقام.",
    "error_upload_all_docs": "الرجاء رفع جميع المستندات المطلوبة (الإقامة، الرخصة، الصورة الشخصية).",
    "autoPasswordNotice": "سيتم إنشاء كلمة المرور تلقائيًا (آخر 4 أرقام من المعرف).",
    "table_employmentStatus": "الحالة الوظيفية",
    "table_actions": "إجراءات",
    "markAsResigned": "تحديد كمستقيل",
    "confirmResignation": "تأكيد الاستقالة",
    "areYouSureMarkResigned": "هل أنت متأكد أنك تريد تحديد هذا المندوب كمستقيل؟ سيتم نقله إلى قسم المستقيلين.",
    "noActiveDelegates": "لا يوجد مناديب نشطون حالياً.",
    "noResignedDelegates": "لا يوجد مناديب مستقيلون حالياً.",
    "hr_primaryGoal": "استقطاب المواهب والإعداد",
    "hr_primaryGoalAdvice": "إعداد المندوب الجديد للنجاح يبدأ من اليوم الأول. استثمر في توجيهه وتدريبه بشكل فعال.",
    "hr_tipOfTheDay": "الاحتفاظ بالموظفين ورضاهم",
    "hr_tipOfTheDayAdvice": "التواصل المستمر والاستماع لملاحظات المناديب يبني الولاء ويقلل من معدل الدوران الوظيفي.",
    "hr_successIndicator": "الامتثال والتوثيق",
    "hr_successIndicatorAdvice": "تأكد من تحديث جميع مستندات المناديب بانتظام لتجنب أي مشاكل قانونية أو تشغيلية.",
    "notifications": "الإشعارات",
    "documentStatusSummary": "ملخص حالة المستندات",
    "valid": "سارية",
    "expiringSoon": "على وشك الانتهاء",
    "expired": "منتهية",
    "delegateDocuments": "مستندات المناديب",
    "iqamaStatus": "حالة الإقامة",
    "licenseStatus": "حالة الرخصة",
    "expiryDate": "تاريخ الانتهاء",
    "noUrgentNotifications": "لا توجد تنبيهات عاجلة",
    "iqamaExpiresSoon": "إقامة {delegateName} ستنتهي قريباً",
    "licenseExpiresSoon": "رخصة {delegateName} ستنتهي قريباً",
    "iqamaExpired": "إقامة {delegateName} منتهية الصلاحية",
    "licenseExpired": "رخصة {delegateName} منتهية الصلاحية",
    "viewDetails": "عرض التفاصيل",
    "iqamaExpiryDate": "تاريخ انتهاء الإقامة",
    "licenseExpiryDate": "تاريخ انتهاء الرخصة",
    "section_basicInfo": "معلومات المندوب الأساسية",
    "section_jobDetails": "التفاصيل الوظيفية",
    "section_officialDocs": "المستندات الرسمية",
    "approveAndSendReport": "اعتماد وإرسال التقرير اليومي",
    "confirmReportSubmissionTitle": "تأكيد إرسال التقرير",
    "confirmReportSubmissionMessage": "هل أنت متأكد من اعتماد بيانات اليوم؟ لا يمكن التعديل على التقرير بعد إرساله.",
    "reportSubmittedSuccessfully": "تم إرسال التقرير اليومي بنجاح!",
    "reportAlreadySubmitted": "تم إرسال تقرير اليوم بالفعل.",
    "operationalDate": "تاريخ اليوم التشغيلي",
    "reportForPeriod": "تقرير عن الفترة",
    "reportForDate": "تقرير لتاريخ",
    "archivedReportTitle": "عرض تقرير مؤرشف لـ",
    "noReportForThisDate": "لم يتم العثور على تقرير معتمد لهذا اليوم.",
    "returnToToday": "العودة لعرض اليوم",
    "advancedPerformanceAnalysis": "تحليل الأداء المتقدم",
    "last7Days": "آخر 7 أيام",
    "last30Days": "آخر 30 يوماً",
    "thisMonth": "هذا الشهر",
    "totalOrders": "إجمالي الطلبات",
    "avgDailyOrders": "متوسط الطلبات اليومي",
    "overallAttendance": "معدل الحضور العام",
    "topPerformer": "أفضل أداء",
    "topPerformingDelegates": "أفضل المناديب أداءً",
    "table_totalOrders": "إجمالي الطلبات",
    "table_avgOrders": "المتوسط اليومي",
    "table_attendanceRate": "نسبة الحضور",
    "table_weekendAbsences": "غياب نهاية الأسبوع",
    "noDataForPeriod": "لا توجد بيانات تقارير معتمدة في الفترة المحددة.",
    "showAdvancedPerformanceAnalysis": "عرض تحليل الأداء المتقدم",
    "hideAdvancedPerformanceAnalysis": "إخفاء التحليل",
    "delegate_welcome_title": "مرحباً بك مجدداً!",
    "delegate_welcome_subtitle": "يوم جديد، فرصة جديدة للإنجاز.",
    "delegate_peak_hours_title": "التركيز على أوقات الذروة",
    "delegate_peak_hours_desc": "من 12 ظهراً إلى 4 عصراً، ومن 7 مساءً إلى 3 فجراً هي أكثر الأوقات طلباً. تواجدك يضمن لك تحقيق أهدافك.",
    "delegate_daily_goal_title": "هدف اليوم: 15 طلبًا",
    "delegate_daily_goal_desc": "كل طلب تسلمه هو خطوة نحو النجاح. أنت قادر على تحقيق الهدف وزيادة دخلك اليوم.",
    "my_requests": "طلباتي",
    "create_new_request": "إنشاء طلب جديد",
    "request_topic": "موضوع الطلب",
    "request_topic_Leave": "طلب إجازة",
    "request_topic_Financial": "طلب سلفة مالية",
    "request_topic_Clearance": "طلب إخلاء طرف",
    "request_topic_ConfidentialComplaint": "شكوى سرية وخاصة",
    "request_topic_ContactSupervisor": "تواصل المشرف / مشكلة تقنية",
    "request_topic_Other": "أخرى / استفسار عام",
    "request_details": "تفاصيل الطلب",
    "attach_supporting_document": "إرفاق مستند داعم",
    "file_not_selected": "لم يتم اختيار أي ملف",
    "submit_request": "إرسال الطلب",
    "request_submitted_successfully": "تم رفع طلبك بنجاح. رقم الطلب هو {requestNumber}",
    "request_status": "حالة الطلب",
    "request_number": "رقم الطلب",
    "view_request_progress": "اضغط لعرض مراحل تقدم الطلب",
    "request_progress_map": "خريطة تتبع مراحل الطلب",
    "no_requests_submitted": "لم تقم بتقديم أي طلبات بعد.",
    "delegate_online": "تنبيه: المندوب {delegateName} بدأ دوامه الآن.",
    "delegate_offline": "تنبيه: المندوب {delegateName} أنهى دوامه الآن.",
    "supervisor_notification_online": "سيتم إرسال إشعار للمشرف ببدء دوامك.",
    "supervisor_notification_offline": "سيتم إرسال إشعار للمشرف بإنهاء دوامك.",
    "delegate": "مندوب",
    "stage_Created": "إنشاء الطلب",
    "stage_OpsSupervisor": "الإدارة التشغيلية",
    "stage_MovementManager": "مدير الحركة",
    "stage_HR": "الموارد البشرية",
    "stage_GeneralManager": "المدير العام",
    "stage_Finance": "الإدارة المالية",
    "tab_incoming": "طلبات واردة",
    "tab_mySent": "طلباتي المرسلة",
    "tab_allRequests": "كل الطلبات",
    "requestDetails": "تفاصيل الطلب",
    "requestHistory": "سجل الطلب",
    "actions": "الإجراءات",
    "approveAndForward": "موافقة وتمرير",
    "reject": "رفض",
    "resolveAndClose": "حل وإغلاق",
    "addReasonPlaceholder": "إضافة سبب أو تعليق (إلزامي عند الرفض)",
    "submitAction": "تنفيذ الإجراء",
    "history_Created": "أنشأ الطلب",
    "history_Approved": "وافق على الطلب",
    "history_Rejected": "رفض الطلب",
    "history_Commented": "أضاف تعليقًا",
    "history_ResolvedAndClosed": "حل وأغلق الطلب",
    "history_Cancelled": "تم إلغاء الطلب تلقائيًا لعدم اتخاذ إجراء.",
    "history_ResolvedAndDirected": "حل الطلب ووجهه إلى",
    "history_DirectiveViewed": "تم الاطلاع على التوجيه",
    "history_DirectiveReplied": "تم الرد على التوجيه",
    "system": "النظام",
    "currentStage": "المرحلة الحالية",
    "status_PendingApproval": "بانتظار الموافقة",
    "status_Approved": "تمت الموافقة",
    "status_Rejected": "مرفوض",
    "status_Completed": "مكتمل",
    "status_Cancelled": "ملغي",
    "error_rejectionReasonRequired": "سبب الرفض إلزامي.",
    "request_type_Internal": "داخلي",
    "request_type_Employee": "موظف",
    "request_type_DirectDirective": "توجيه مباشر",
    "gm_primaryGoal": "النمو الاستراتيجي",
    "gm_primaryGoalAdvice": "وازن بين الكفاءة التشغيلية ورضا الموظفين. استخدم التقارير لاتخاذ قرارات شاملة تدعم الرؤية طويلة الأمد.",
    "gm_tipOfTheDay": "تمكين القادة",
    "gm_tipOfTheDayAdvice": "فوض الصلاحيات لمدراء الأقسام وثق في قراراتهم. دورك هو توجيه الرؤية وإزالة العوائق.",
    "gm_successIndicator": "ثقافة البيانات",
    "gm_successIndicatorAdvice": "شجع على استخدام لوحات التحليل والتقارير في جميع الإدارات. القرارات المبنية على البيانات هي أساس النجاح المستدام.",
    "mm_primaryGoal": "الكفاءة التشغيلية القصوى",
    "mm_primaryGoalAdvice": "حلل بيانات الأداء لتحديد نقاط الاختناق. هدفك هو تقليل وقت التوقف وزيادة عدد الطلبات لكل ساعة.",
    "mm_tipOfTheDay": "التواصل الميداني",
    "mm_tipOfTheDayAdvice": "ابق على تواصل مستمر مع المشرفين فهم عيناك وأذناك في الميدان.",
    "mm_successIndicator": "الاستجابة السريعة",
    "mm_successIndicatorAdvice": "قدرتك على حل المشكلات التشغيلية بسرعة هي مؤشر نجاحك. استخدم قسم الطلبات لمتابعة المشاكل التقنية.",
    "fin_primaryGoal": "الدقة المالية",
    "fin_primaryGoalAdvice": "ضمان دقة جميع المعاملات المالية، من رواتب المناديب إلى مستحقات نهاية الأسبوع.",
    "fin_tipOfTheDay": "التحليل المالي",
    "fin_tipOfTheDayAdvice": "حلل تقارير الأداء من منظور مالي. هل هناك علاقة بين أداء المندوب والتكاليف التشغيلية؟",
    "fin_successIndicator": "الشفافية",
    "fin_successIndicatorAdvice": "توفير تقارير مالية واضحة ودقيقة للإدارة العليا يدعم اتخاذ القرارات الاستراتيجية.",
    "legal_primaryGoal": "الامتثال القانوني",
    "legal_primaryGoalAdvice": "هدفنا الأساسي هو ضمان أن جميع عملياتنا وعقودنا تتوافق مع الأنظمة والقوانين السعودية.",
    "legal_tipOfTheDay": "الوقاية خير من العلاج",
    "legal_tipOfTheDayAdvice": "راجع العقود والسياسات الداخلية بشكل دوري لتجنب أي ثغرات قانونية قد تظهر مستقبلاً.",
    "legal_successIndicator": "إدارة المخاطر",
    "legal_successIndicatorAdvice": "نجاحك يقاس بقدرتك على تحديد المخاطر القانونية المحتملة ووضع استراتيجيات استباقية للتعامل معها.",
    "aiPerformanceSummary": "ملخص الأداء بالذكاء الاصطناعي",
    "generatingAnalysis": "جاري إنشاء التحليل...",
    "error_ai_analysis_failed": "فشل تحليل الذكاء الاصطناعي. الرجاء المحاولة مرة أخرى في وقت لاحق.",
    "ordersTrend": "توجه الطلبات",
    "topDelegatesByOrders": "أفضل 5 مناديب (حسب الطلبات)",
    "efficiency_orders_per_hour": "الكفاءة (طلب/ساعة)",
    "performanceTier": "مستوى الأداء",
    "tier_Excellent": "ممتاز",
    "tier_Average": "متوسط",
    "tier_Weak": "ضعيف",
    "delegatePerformanceAnalysis": "تحليل أداء المندوب",
    "dailyPerformance": "الأداء اليومي",
    "close": "إغلاق",
    "resolveAndDirect": "حل وتوجيه",
    "directiveComment": "تعليق التوجيه",
    "directToDepartment": "توجيه إلى إدارة",
    "confirmResolveAndDirect": "تأكيد الحل والتوجيه",
    "followUpOnRequest": "متابعة للطلب رقم",
    "basedOnDirectionFrom": "بناءً على توجيه من",
    "originalRequestDetails": "تفاصيل الطلب الأصلي",
    "circulars": "التعاميم",
    "createNewCircular": "إنشاء تعميم جديد",
    "circularTitle": "عنوان التعميم",
    "circularContent": "محتوى التعميم",
    "targetAudience": "الجمهور المستهدف",
    "audience_all": "جميع الموظفين",
    "audience_delegates": "المناديب فقط",
    "author": "الناشر",
    "date": "التاريخ",
    "noCirculars": "لا توجد تعاميم حاليًا.",
    "addUser": "إضافة موظف",
    "userName": "اسم الموظف",
    "userRole": "الدور الوظيفي",
    "idExpiryDate": "تاريخ انتهاء الهوية",
    "noUsersFound": "لم يتم العثور على موظفين.",
    "section_personalInfo": "المعلومات الشخصية",
    "section_jobAndLogin": "معلومات الوظيفة والدخول",
    "section_documents": "المستندات الرسمية",
    "error_noSupervisors_title": "تنبيه: لا يوجد مشرفون",
    "error_noSupervisors_body": "يجب إضافة مشرف واحد على الأقل من قسم 'إدارة الموظفين' قبل أن تتمكن من إضافة مندوب جديد.",
    "activity_Present": "حاضر",
    "activity_Absent": "غائب",
    "activity_OnLeave": "إجازة",
    "selectTargetDepartment": "اختر الإدارة المستهدفة",
    "internalRequestTitlePlaceholder": "مثال: طلب صيانة لمركبة",
    "operationalDepartment": "القسم التشغيلي",
    "selectOperationalDepartment": "اختر القسم التشغيلي",
    "selectSupervisor": "اختر المشرف",
    "assignedDelegates": "المناديب المسجلون",
    "autoPasswordStaffNotice": "سيتم تعيين كلمة المرور تلقائيياً لتكون رقم الهوية. يجب على الموظف تغييرها عند تسجيل الدخول.",
    "changePassword": "تغيير كلمة المرور",
    "changePasswordRequired": "يجب عليك تعيين كلمة مرور جديدة خاصة بك قبل المتابعة.",
    "newPassword": "كلمة المرور الجديدة",
    "confirmPassword": "تأكيد كلمة المرور",
    "passwordChangedSuccess": "تم تغيير كلمة المرور بنجاح.",
    "error_passwordsDoNotMatch": "كلمتا المرور غير متطابقتين.",
    "setNewPassword": "تعيين كلمة المرور",
    "carPlateNumber": "رقم لوحة السيارة",
    "rentalCompany": "شركة التأجير",
    "suspensionDate": "تاريخ التوقف",
    "returnDate": "تاريخ الاستئناف",
    "indefinite": "غير محدد",
    "resumeWork": "استئناف العمل",
    "confirmResume": "تأكيد الاستئناف",
    "resumeDelegateMessage": "هل أنت متأكد من إعادة المندوب للعمل؟ سيتم تغيير حالته إلى نشط.",
    "suspendDelegateModalTitle": "إيقاف المندوب",
    "optional": "(اختياري)",
    "markAsRead": "تحديد كمقروء",
    "markAllAsRead": "تحديد الكل كمقروء",
    "searchRequestsPlaceholder": "ابحث برقم الطلب أو العنوان",
    "filterByStatus": "تصفية حسب الحالة",
    "all": "الكل",
    "tab_directives": "توجيهات مباشرة",
    "warning_72h_close": "تنبيه هام: سيتم إغلاق الطلب آلياً بعد 72 ساعة.",
    "warning_72h_detail": "سيتم إغلاق الطلب خلال 72 ساعة، وبعد إغلاقه لا يتم اتخاذ أي إجراءات نهائية من قبل أي جهة أخرى. في حال الإغلاق دون إجراء، سيظهر الرد: تم انتهاء مهلة الطلب.",
    "createDirectDirective": "إنشاء توجيه مباشر",
    "selectTargetDelegate": "اختر المندوب المستهدف",
    "directiveTitlePlaceholder": "مثال: توجيه بخصوص الالتزام بالزي",
    "submitDirective": "إرسال التوجيه",
    "status_Expired": "منتهي الصلاحية",
    "respondToDirective": "الرد على التوجيه",
    "directiveResponse_Viewed": "تم الاطلاع",
    "directiveResponse_Replied": "تم الرد",
    "commentRequired": "الملاحظة مطلوبة",
    "confirmDirectiveResponse": "تأكيد وإرسال",
    "useFormalTemplate": "استخدام نموذج رسمي",
    "template_GeneralRequest": "نموذج طلب عام",
    "template_Complaint": "نموذج شكوى",
    "template_Financial": "نموذج مالي",
    "template_GeneralRequest_Text": "السادة إدارة [اسم الإدارة] المحترمين،\n\nالسلام عليكم ورحمة الله وبركاته،\n\nأتقدم إليكم بطلبي هذا بخصوص [الموضوع]، حيث أنني [الشرح].\n\nآمل منكم التكرم بالنظر في طلبي.\n\nولكم جزيل الشكر.",
    "template_Complaint_Text": "السادة إدارة [اسم الإدارة] المحترمين،\n\nالسلام عليكم ورحمة الله وبركاته،\n\nأفيدكم بأنني واجهت مشكلة بخصوص [الموضوع]، وتفاصيلها كالتالي: [الشرح].\n\nأرجو التكرم بحل المشكلة في أقرب وقت ممكن.\n\nوتقبلوا تحياتي.",
    "template_Financial_Text": "السادة الإدارة المالية المحترمين،\n\nالسلام عليكم ورحمة الله وبركاته،\n\nأتقدم بطلب [سلفة/مستحقات] بمبلغ وقدره [المبلغ]، وذلك بسبب [السبب].\n\nشاكرين لكم حسن تعاونكم.",
    "no_directives": "لا توجد توجيهات مباشرة حالياً.",
    "responseComment": "ملاحظات الرد",
    "duplicateWarning": "تحذير: بيانات مكررة",
    "duplicateWarningMessage": "يوجد بالفعل مندوب مسجل بـ:",
    "verificationRequired": "التحقق الإلزامي",
    "verificationStep1": "خطوة 1: التحقق من الوجه",
    "verificationStep2": "خطوة 2: التحقق من المركبة",
    "takeSelfie": "التقاط صورة سيلفي",
    "takeCarPhoto": "التقاط صورة السيارة",
    "verifying": "جاري التحقق...",
    "faceMatchSuccess": "تم التحقق من الهوية بنجاح.",
    "faceMatchFailed": "فشل التحقق من الهوية. الصورة غير مطابقة.",
    "carCheckSuccess": "تم التحقق من السيارة بنجاح.",
    "carCheckFailed": "فشل التحقق من السيارة. الصورة لا تبدو كسيارة.",
    "verificationComplete": "تم إكمال عملية التحقق.",
    "instructionFace": "الرجاء التقاط صورة واضحة لوجهك للمطابقة مع الملف الشخصي.",
    "instructionCar": "الرجاء التقاط صورة أمامية واضحة لسيارتك.",
    "faceCapture": "صورة الوجه الحية",
    "carCapture": "صورة السيارة الحية",
    "liveVerification": "تحقق حي",
    "continue": "متابعة",
    "filterBySupervisor": "تصفية حسب المشرف",
    "allSupervisors": "كل المشرفين",
    "request_timeout_msg": "تم انتهاء مهلة الطلب",
    "suspended": "موقوف",
    "registerLeave": "تسجيل إجازة",
    "status_Suspended": "موقوف",
    "currentStatus": "الحالة الحالية",
    "status_Active": "نشط",
    "status_Resigned": "مستقيل",
    "acknowledgeAndReply": "تم الرد والاطلاع",
    "finalResponse": "الرد النهائي",
    "openAttachment": "فتح المرفق",
    "download": "تحميل",
    "assignmentDetails": "بيانات التعيين",
    "vehicleDetails": "بيانات المركبة",
    "statusAndTenure": "الحالة الوظيفية",
};

const enTranslations: Record<string, string> = {
    // Basic English Fallback
    "appTitle": "Imdad Al-Tatawor",
    "appSubtitle": "Logistics Services",
    "login": "Login",
    "password": "Password",
    "chooseYourRole": "Choose Your Role",
    "selectSupervisor": "Select Supervisor",
    "selfPreparation": "Self Preparation",
    "verificationRequired": "Verification Required",
    "takeSelfie": "Take Selfie",
    "takeCarPhoto": "Take Car Photo",
    "verifying": "Verifying...",
    "faceMatchSuccess": "Face Verified",
    "faceMatchFailed": "Face Verification Failed",
    "carCheckSuccess": "Car Verified",
    "carCheckFailed": "Car Verification Failed",
    "verificationComplete": "Verification Complete",
    "instructionFace": "Take a clear photo of your face.",
    "instructionCar": "Take a clear photo of your car.",
    "duplicateWarning": "Duplicate Data Warning",
    "duplicateWarningMessage": "Delegate already exists with:",
    "continue": "Continue",
    "tab_directives": "Direct Directives",
    "directiveResponse_Viewed": "Viewed",
    "directiveResponse_Replied": "Replied",
    "markAsRead": "Mark as Read",
    "markAllAsRead": "Mark All as Read",
    "changePassword": "Change Password",
    "joinDate": "Join Date",
    "filterBySupervisor": "Filter by Supervisor",
    "allSupervisors": "All Supervisors",
    "warning_72h_close": "Warning: Request will be closed after 72h.",
    "warning_72h_detail": "The request will be closed after 72 hours. After closure, no further action can be taken by any party. If closed without action, the status will be 'Request Timeout'.",
    "request_timeout_msg": "Request Timeout",
    "suspended": "Suspended",
    "registerLeave": "Register Leave",
    "status_Suspended": "Suspended",
    "currentStatus": "Current Status",
    "status_Active": "Active",
    "status_Resigned": "Resigned",
    "resignationDate": "Resignation Date",
    "acknowledgeAndReply": "Acknowledge & Reply",
    "finalResponse": "Final Response",
    "nationalId": "National ID",
    "openAttachment": "Open Attachment",
    "download": "Download",
    "assignmentDetails": "Assignment Details",
    "vehicleDetails": "Vehicle Details",
    "statusAndTenure": "Status & Tenure",
};

const urTranslations: Record<string, string> = {
     // Basic Urdu Fallback
    "appTitle": "امداد التطوير",
    "appSubtitle": "لاجسٹکس خدمات",
    "login": "لاگ ان",
    "password": "پاس ورڈ",
    "chooseYourRole": "اپنا کردار منتخب کریں",
    "selectSupervisor": "سپروائزر منتخب کریں",
    "selfPreparation": "خود تیاری",
    "verificationRequired": "تصدیق درکار ہے",
    "takeSelfie": "سیلفی لیں",
    "takeCarPhoto": "گاڑی کی تصویر لیں",
    "verifying": "تصدیق ہو رہی ہے...",
    "faceMatchSuccess": "چہرے کی تصدیق ہو گئی",
    "faceMatchFailed": "چہرے کی تصدیق ناکام",
    "carCheckSuccess": "گاڑی کی تصدیق ہو گئی",
    "carCheckFailed": "گاڑی کی تصدیق ناکام",
    "verificationComplete": "تصدیق مکمل",
    "instructionFace": "اپنے چہرے کی واضح تصویر لیں۔",
    "instructionCar": "اپنی گاڑی کی واضح تصویر لیں۔",
     "duplicateWarning": "ڈپلیکیٹ ڈیٹا وارننگ",
    "duplicateWarningMessage": "نمائندہ پہلے ہی موجود ہے:",
    "continue": "جاری رکھیں",
    "tab_directives": "براہ راست ہدایات",
    "directiveResponse_Viewed": "دیکھا گیا",
    "directiveResponse_Replied": "جواب دیا گیا",
     "markAsRead": "بطور پڑھا ہوا نشان زد کریں",
    "markAllAsRead": "سب کو پڑھا ہوا نشان زد کریں",
    "changePassword": "پاس ورڈ تبدیل کریں",
    "joinDate": "شمولیت کی تاریخ",
    "filterBySupervisor": "سپروائزر کے لحاظ سے فلٹر کریں",
    "allSupervisors": "تمام سپروائزرز",
    "warning_72h_close": "انتباہ: درخواست 72 گھنٹے بعد بند ہو جائے گی۔",
    "warning_72h_detail": "اگر 72 گھنٹے میں کوئی کارروائی نہ ہوئی تو درخواست خود بخود بند ہو جائے گی۔",
    "request_timeout_msg": "درخواست کا وقت ختم ہوگیا",
    "suspended": "معطل",
    "registerLeave": "چھٹی درج کریں",
    "status_Suspended": "معطل",
    "currentStatus": "موجودہ حیثیت",
    "status_Active": "فعال",
    "status_Resigned": "مستعفی",
    "resignationDate": "استعفیٰ کی تاریخ",
    "acknowledgeAndReply": "تسلیم کریں اور جواب دیں",
    "finalResponse": "حتمی جواب",
    "nationalId": "قومی شناخت",
    "openAttachment": "منسلکہ کھولیں",
    "download": "ڈاؤن لوڈ کریں",
    "assignmentDetails": "تعیناتی کی تفصیلات",
    "vehicleDetails": "گاڑی کی تفصیلات",
    "statusAndTenure": "حیثیت اور مدت",
};

interface LanguageContextType {
    language: string;
    setLanguage: (lang: string) => void;
    t: (key: string, params?: any) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
    children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
    const [language, setLanguage] = useState('ar');

    const translations = useMemo(() => {
        switch (language) {
            case 'en': return enTranslations;
            case 'ur': return urTranslations;
            default: return arTranslations;
        }
    }, [language]);

    const t = useCallback((key: string, params?: any) => {
        let text = translations[key] || key;
        if (params) {
            Object.keys(params).forEach(param => {
                text = text.replace(`{${param}}`, params[param]);
            });
        }
        return text;
    }, [translations]);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};